// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: booksRecommended.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBooksRecommendedByUser = `-- name: GetBooksRecommendedByUser :many
SELECT 
  id,
  isbn,
  title,
  description,
  picture,
  userId,
  createdAt
FROM booksRecommended
WHERE userId = $1
`

func (q *Queries) GetBooksRecommendedByUser(ctx context.Context, userid pgtype.UUID) ([]Booksrecommended, error) {
	rows, err := q.db.Query(ctx, getBooksRecommendedByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booksrecommended
	for rows.Next() {
		var i Booksrecommended
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Description,
			&i.Picture,
			&i.Userid,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBooksRecommended = `-- name: SaveBooksRecommended :exec
INSERT INTO booksRecommended (
  id,
  isbn,
  title,
  description,
  picture,
  userId
) VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveBooksRecommendedParams struct {
	ID          uuid.UUID
	Isbn        string
	Title       string
	Description pgtype.Text
	Picture     pgtype.Text
	Userid      pgtype.UUID
}

func (q *Queries) SaveBooksRecommended(ctx context.Context, arg SaveBooksRecommendedParams) error {
	_, err := q.db.Exec(ctx, saveBooksRecommended,
		arg.ID,
		arg.Isbn,
		arg.Title,
		arg.Description,
		arg.Picture,
		arg.Userid,
	)
	return err
}
