// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: booksToRead.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const saveBooksToRead = `-- name: SaveBooksToRead :exec
INSERT INTO booksToRead (
  id,
  isbn,
  title,
  description,
  picture,
  userId
) VALUES ( $1, $2, $3, $4, $5, $6 )
`

type SaveBooksToReadParams struct {
	ID          uuid.UUID
	Isbn        string
	Title       string
	Description pgtype.Text
	Picture     pgtype.Text
	Userid      pgtype.UUID
}

func (q *Queries) SaveBooksToRead(ctx context.Context, arg SaveBooksToReadParams) error {
	_, err := q.db.Exec(ctx, saveBooksToRead,
		arg.ID,
		arg.Isbn,
		arg.Title,
		arg.Description,
		arg.Picture,
		arg.Userid,
	)
	return err
}
