// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booksrecommended struct {
	ID          uuid.UUID
	Isbn        string
	Title       string
	Description pgtype.Text
	Picture     pgtype.Text
	Userid      pgtype.UUID
	Createdat   pgtype.Timestamp
}

type Bookstoread struct {
	ID          uuid.UUID
	Isbn        string
	Title       string
	Description pgtype.Text
	Picture     pgtype.Text
	Userid      pgtype.UUID
	Createdat   pgtype.Timestamp
}

type Comment struct {
	ID          uuid.UUID
	Content     string
	Postid      pgtype.UUID
	Commentedby pgtype.UUID
	Createdat   pgtype.Timestamp
}

type Post struct {
	ID        uuid.UUID
	Comment   string
	Postedby  pgtype.UUID
	Createdat pgtype.Timestamp
}

type User struct {
	ID          uuid.UUID
	Name        string
	Picture     string
	Description pgtype.Text
	Mail        string
	Createdat   pgtype.Timestamp
}

type UserFollower struct {
	UserID     uuid.UUID
	FollowerID uuid.UUID
	CreatedAt  pgtype.Timestamptz
}
